### ISSUE TITLE
The get_url module doesn't enforce the mode parameter if the file already exists

### ISSUE THREAD

**Issue by lparkes** [lparkes/ansible#5]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```

```

##### STEPS TO REPRODUCE

```yaml
- get_url:
  url: ...
  dest: ...
  owner: root
  group: root
  mode: 0644
  sha256sum: ...
```

Decide that the mode should be 0755 and update your playbook. When you rerun the playbook, the file that was already downloaded doesn't have its permissions updated.

##### ACTUAL RESULTS

```

```
